### ISSUE TITLE
What does zRange do?

### ISSUE THREAD

**Issue by cruzsbrian** [bobbigmac/gravity#1]
Can you walk me through zRange and zShare? It kind of looks like you're using them to have the perspective and coloring scaled to maximums and minimums on each frame. The main thing that's confusing me is the use of objects and numbers in a boolean statement, and then the `|| false` part. I'm more used to strongly typed languages.

**Comment by bobbigmac** [comment]
`zRange` stores the depth of the furthest and nearest particle in the scene. `zShare` is assigned to each particle as it renders based on its own depth relative to those, this allows a hsl [colour to be generated](https://github.com/bobbigmac/gravity/blob/master/grav.js#L58) to indicate its depth to the viewer, and to [slightly affect its scale](https://github.com/bobbigmac/gravity/blob/master/grav.js#L62).

The `|| false` part in the [zRange builder](https://github.com/bobbigmac/gravity/blob/master/grav.js#L78) is now redundant, as it just assigns a false if either the particle does not exist (there previously were some conditions looking for `=== false` that I removed), or the particle exists but has  a falsey z property (should not happen). It's shorthand for accessing object members with a fallback/default value.

The nearest/furthest thing technically works, but still could do with some tweaks to account for a single stray particle being very much out of the depth containing most particles, hence why when dropping a cloud, the entire scene tends to become mostly one colour, with only a couple of differently coloured particles visible. I had tried weighting them based on proximity to the median, but couldn't do it in a performant way without caching or ballparking.

**Comment by cruzsbrian** [comment]
Ah, I see. I think the issue of stray particles is not one with zRange/zShare, but with your cloud generation code. Using tangent to get a Z value will almost certainly put most of the particles near the center and one or two very far away. See the tangent graph below.
![image](https://cloud.githubusercontent.com/assets/10601213/17385079/4b37c45a-59ae-11e6-8698-eaece0a00d3d.png)

I've been messing around with my own 3d gravity simulator (I rewrote the code from scratch, so its still missing a lot of the features this project has). A better way to do it is by generating two angles, like how stars are positioned in the sky:
![image](https://cloud.githubusercontent.com/assets/10601213/17385340/fd172034-59af-11e6-85f7-b37e23543af5.png)
Then you can get the coordinates for a point using [this code](https://github.com/cruzsbrian/gravity-3d/blob/master/ui.js#L30). Angle 1 is the altitude and angle 2 is the azimuth.

**Comment by bobbigmac** [comment]
Ah I see, that's really helpful, thanks!
I'm not much of a math person, was just kinda poking around and it gave something kinda like what I was after ;) Will tweak at some point to something sensible as you suggest.

**Comment by bobbigmac** [comment]
btw, you have full-write here, since it's based of yours with 'dwyl' license, but couldn't find a repo. Feel free to mod if you like, I know I b0rked a couple bits hacking around, but not hugely different :)

**Comment by cruzsbrian** [comment]
Yeah, absolutely. I plan to at some point. When it came to doing panning
and rotation in 3d I thought about making a new branch for it, but so much
would have been needed to be changed that it was easier to just start
fresh. Now that I have it working though, I'll probably shove it into this
repo.

**Comment by bobbigmac** [comment]
I had tried to render it in proper 3d with webgl to support 3d rotation, but not something I'm slick enough with to do it in a reasonable number of lines of code.

**Comment by cruzsbrian** [comment]
Oh I just gave up on webgl.

**Comment by bobbigmac** [comment]
Added a quick fix with the code you linked (and a vy). I'm not sure what the difference is on the math side, but seems to work much better when generating clouds. Thanks! :)
